name: Review

on:
  pull_request_target:

env:
  # GitHub Actions Runner is not a tty therefore lots of tools disable colour
  # The webview supports ANSI colour so we try to add colour support here
  #| env var                         | supported by      |
  FORCE_COLOR: "true"                # nox,pip,pytest,mypy
  PRE_COMMIT_COLOR: "always"         # pre-commit

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
      - name: lint
        run: rye lint


  integration-tests:
    runs-on: ubuntu-latest
    name: GitHub Actions Integration Tests
    permissions:
      id-token: write
      security-events: write
      actions: read
      contents: read
    environment: main
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::531249009620:role/Deploy
          aws-region: eu-west-1
      - uses: ./
